from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    MODEL_NOT_CONFIGURED = "MODEL_NOT_CONFIGURED"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    MODEL_ROUTE_NOT_FOUND = "MODEL_ROUTE_NOT_FOUND"
    MODEL_ROUTE_BLOCKED_BY_PRIVACY = "MODEL_ROUTE_BLOCKED_BY_PRIVACY"
    MODEL_TIMEOUT = "MODEL_TIMEOUT"
    MODEL_STREAM_INTERRUPTED = "MODEL_STREAM_INTERRUPTED"
    MODEL_AUTH_FAILED = "MODEL_AUTH_FAILED"
    MODEL_CONTEXT_TOO_LARGE = "MODEL_CONTEXT_TOO_LARGE"
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
    MODEL_PROTOCOL_ERROR = "MODEL_PROTOCOL_ERROR"
    TURN_CANCELLED = "TURN_CANCELLED"
    CHAT_RUNTIME_FAILED = "CHAT_RUNTIME_FAILED"
    CONTEXT_BUILD_FAILED = "CONTEXT_BUILD_FAILED"
    RESPONSE_COMPOSE_FAILED = "RESPONSE_COMPOSE_FAILED"
    ASSET_PERMISSION_DENIED = "ASSET_PERMISSION_DENIED"
    ASSET_NOT_FOUND = "ASSET_NOT_FOUND"
    ASSET_DISABLED = "ASSET_DISABLED"
    ASSET_ACCESS_DENIED = "ASSET_ACCESS_DENIED"
    ASSET_HANDLE_INVALID = "ASSET_HANDLE_INVALID"
    ASSET_HANDLE_EXPIRED = "ASSET_HANDLE_EXPIRED"
    CAPABILITY_DENIED = "CAPABILITY_DENIED"
    KNOWLEDGE_SOURCE_NOT_FOUND = "KNOWLEDGE_SOURCE_NOT_FOUND"
    KNOWLEDGE_INDEX_FAILED = "KNOWLEDGE_INDEX_FAILED"
    KNOWLEDGE_SEARCH_FAILED = "KNOWLEDGE_SEARCH_FAILED"
    SECRET_REF_NOT_FOUND = "SECRET_REF_NOT_FOUND"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    SAFETY_BLOCKED = "SAFETY_BLOCKED"
    TOOL_FAILED = "TOOL_FAILED"
    MCP_UNAVAILABLE = "MCP_UNAVAILABLE"
    MEMORY_WRITE_REJECTED = "MEMORY_WRITE_REJECTED"
    MEMORY_EXTRACT_FAILED = "MEMORY_EXTRACT_FAILED"
    MEMORY_WRITE_FAILED = "MEMORY_WRITE_FAILED"
    MEMORY_SEARCH_FAILED = "MEMORY_SEARCH_FAILED"
    MEMORY_VECTOR_SYNC_FAILED = "MEMORY_VECTOR_SYNC_FAILED"
    MEMORY_CONFLICT_CHECK_FAILED = "MEMORY_CONFLICT_CHECK_FAILED"
    MEMORY_CORRECTION_FAILED = "MEMORY_CORRECTION_FAILED"
    MEMORY_ACCESS_DENIED = "MEMORY_ACCESS_DENIED"
    MEMORY_NOT_FOUND = "MEMORY_NOT_FOUND"
    MEMORY_POLICY_BLOCKED = "MEMORY_POLICY_BLOCKED"
    TASK_STATE_INVALID = "TASK_STATE_INVALID"
    TASK_PLAN_FAILED = "TASK_PLAN_FAILED"
    TASK_PRECHECK_FAILED = "TASK_PRECHECK_FAILED"
    TASK_BUDGET_EXCEEDED = "TASK_BUDGET_EXCEEDED"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_STEP_FAILED = "TASK_STEP_FAILED"
    TASK_RETRY_EXHAUSTED = "TASK_RETRY_EXHAUSTED"
    AGENT_LOOP_FAILED = "AGENT_LOOP_FAILED"
    AGENT_BUDGET_EXHAUSTED = "AGENT_BUDGET_EXHAUSTED"
    TASK_OBSERVATION_FAILED = "TASK_OBSERVATION_FAILED"
    PLANNER_CAPABILITY_UNAVAILABLE = "PLANNER_CAPABILITY_UNAVAILABLE"
    REFLECTION_CANDIDATE_FAILED = "REFLECTION_CANDIDATE_FAILED"
    PLAN_CANDIDATE_INVALID = "PLAN_CANDIDATE_INVALID"
    PLAN_POLICY_PRUNED = "PLAN_POLICY_PRUNED"
    MODEL_PLANNER_UNAVAILABLE = "MODEL_PLANNER_UNAVAILABLE"
    AGENT_NEXT_ACTION_FAILED = "AGENT_NEXT_ACTION_FAILED"
    TOOL_FAILURE_RECOVERY_FAILED = "TOOL_FAILURE_RECOVERY_FAILED"
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    TOOL_SCHEMA_INVALID = "TOOL_SCHEMA_INVALID"
    TOOL_PERMISSION_DENIED = "TOOL_PERMISSION_DENIED"
    TOOL_APPROVAL_REQUIRED = "TOOL_APPROVAL_REQUIRED"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    TOOL_TIMEOUT = "TOOL_TIMEOUT"
    TOOL_OUTPUT_BLOCKED = "TOOL_OUTPUT_BLOCKED"
    APPROVAL_DENIED = "APPROVAL_DENIED"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    ARTIFACT_WRITE_FAILED = "ARTIFACT_WRITE_FAILED"
    ARTIFACT_NOT_FOUND = "ARTIFACT_NOT_FOUND"
    MEDIA_BACKEND_UNAVAILABLE = "MEDIA_BACKEND_UNAVAILABLE"
    MEDIA_ASSET_NOT_FOUND = "MEDIA_ASSET_NOT_FOUND"
    MEDIA_PLAN_INVALID = "MEDIA_PLAN_INVALID"
    MEDIA_RUNTIME_FAILED = "MEDIA_RUNTIME_FAILED"
    PLUGIN_INSTALL_FAILED = "PLUGIN_INSTALL_FAILED"
    PLUGIN_VALIDATE_FAILED = "PLUGIN_VALIDATE_FAILED"
    PLUGIN_PERMISSION_PREVIEW_FAILED = "PLUGIN_PERMISSION_PREVIEW_FAILED"
    PLUGIN_NOT_FOUND = "PLUGIN_NOT_FOUND"
    PLUGIN_DISABLED = "PLUGIN_DISABLED"
    PLUGIN_REVOKED = "PLUGIN_REVOKED"
    SKILL_NOT_FOUND = "SKILL_NOT_FOUND"
    SKILL_DISABLED = "SKILL_DISABLED"
    SKILL_REVOKED = "SKILL_REVOKED"
    SKILL_MATCH_FAILED = "SKILL_MATCH_FAILED"
    SKILL_RUN_FAILED = "SKILL_RUN_FAILED"
    SKILL_EVAL_FAILED = "SKILL_EVAL_FAILED"
    SKILL_CANDIDATE_NOT_FOUND = "SKILL_CANDIDATE_NOT_FOUND"
    MCP_SERVER_NOT_FOUND = "MCP_SERVER_NOT_FOUND"
    MCP_CONNECT_FAILED = "MCP_CONNECT_FAILED"
    MCP_SYNC_FAILED = "MCP_SYNC_FAILED"
    MCP_TOOL_NOT_FOUND = "MCP_TOOL_NOT_FOUND"
    MCP_TOOL_PERMISSION_DENIED = "MCP_TOOL_PERMISSION_DENIED"
    MCP_TOOL_CALL_FAILED = "MCP_TOOL_CALL_FAILED"
    MCP_RESOURCE_UNTRUSTED = "MCP_RESOURCE_UNTRUSTED"
    MCP_PROMPT_BLOCKED = "MCP_PROMPT_BLOCKED"
    EVAL_FAILED = "EVAL_FAILED"
    EVAL_SECURITY_FAILED = "EVAL_SECURITY_FAILED"
    SANDBOX_BLOCKED = "SANDBOX_BLOCKED"
    SUPERVISOR_PLAN_FAILED = "SUPERVISOR_PLAN_FAILED"
    SUPERVISOR_PARTICIPANT_SELECTION_FAILED = "SUPERVISOR_PARTICIPANT_SELECTION_FAILED"
    SUPERVISOR_MODE_UNSUPPORTED = "SUPERVISOR_MODE_UNSUPPORTED"
    PARTICIPANT_NOT_FOUND = "PARTICIPANT_NOT_FOUND"
    PARTICIPANT_UNAVAILABLE = "PARTICIPANT_UNAVAILABLE"
    PARTICIPANT_PERMISSION_DENIED = "PARTICIPANT_PERMISSION_DENIED"
    SUBTASK_CONTEXT_FAILED = "SUBTASK_CONTEXT_FAILED"
    SUBTASK_RUN_FAILED = "SUBTASK_RUN_FAILED"
    SUBTASK_MERGE_FAILED = "SUBTASK_MERGE_FAILED"
    HOST_REVIEW_FAILED = "HOST_REVIEW_FAILED"
    HOST_SYNTHESIS_FAILED = "HOST_SYNTHESIS_FAILED"
    COLLABORATION_ROUND_FAILED = "COLLABORATION_ROUND_FAILED"
    MEMBER_MEMORY_SCOPE_DENIED = "MEMBER_MEMORY_SCOPE_DENIED"
    SHELL_CONFIG_INVALID = "SHELL_CONFIG_INVALID"
    SHELL_TEMPLATE_INVALID = "SHELL_TEMPLATE_INVALID"
    SHELL_SWITCH_BLOCKED = "SHELL_SWITCH_BLOCKED"
    SHELL_FIXED_MENU_VIOLATION = "SHELL_FIXED_MENU_VIOLATION"
    SHELL_BUSINESS_VALUE_MUTATION_BLOCKED = "SHELL_BUSINESS_VALUE_MUTATION_BLOCKED"
    RELEASE_GATE_NOT_FOUND = "RELEASE_GATE_NOT_FOUND"
    RELEASE_GATE_BLOCKED = "RELEASE_GATE_BLOCKED"
    RELEASE_GATE_INVALID_STATE = "RELEASE_GATE_INVALID_STATE"
    FINDING_NOT_FOUND = "FINDING_NOT_FOUND"
    FINDING_BLOCKS_RELEASE = "FINDING_BLOCKS_RELEASE"
    EVAL_SUITE_NOT_FOUND = "EVAL_SUITE_NOT_FOUND"
    EVAL_RUN_FAILED = "EVAL_RUN_FAILED"
    SECURITY_AUDIT_FAILED = "SECURITY_AUDIT_FAILED"
    SECRET_LEAKAGE_DETECTED = "SECRET_LEAKAGE_DETECTED"
    INTEGRITY_CHECK_FAILED = "INTEGRITY_CHECK_FAILED"
    BACKUP_FAILED = "BACKUP_FAILED"
    RESTORE_FAILED = "RESTORE_FAILED"
    BENCHMARK_FAILED = "BENCHMARK_FAILED"
    DIAGNOSTIC_EXPORT_FAILED = "DIAGNOSTIC_EXPORT_FAILED"
    RELEASE_REPORT_FAILED = "RELEASE_REPORT_FAILED"
    SAFETY_DECISION_NOT_FOUND = "SAFETY_DECISION_NOT_FOUND"
    VECTOR_SYNC_FAILED = "VECTOR_SYNC_FAILED"
    VECTOR_PROVIDER_UNAVAILABLE = "VECTOR_PROVIDER_UNAVAILABLE"
    PERSONA_PROFILE_NOT_FOUND = "PERSONA_PROFILE_NOT_FOUND"
    HEART_STATE_NOT_FOUND = "HEART_STATE_NOT_FOUND"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    CONFIG_ERROR = "CONFIG_ERROR"


class ReleaseGateStatus(StrEnum):
    CREATED = "created"
    COLLECTING_EVIDENCE = "collecting_evidence"
    RUNNING_EVALS = "running_evals"
    RUNNING_SECURITY_AUDIT = "running_security_audit"
    RUNNING_PERFORMANCE = "running_performance"
    RUNNING_BACKUP_RESTORE = "running_backup_restore"
    REVIEWING_FINDINGS = "reviewing_findings"
    BLOCKED = "blocked"
    READY_FOR_RELEASE = "ready_for_release"
    RELEASED = "released"
    ARCHIVED = "archived"


class FindingSeverity(StrEnum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class FindingStatus(StrEnum):
    OPEN = "open"
    TRIAGED = "triaged"
    FIX_IN_PROGRESS = "fix_in_progress"
    FIXED = "fixed"
    VERIFIED = "verified"
    ACCEPTED_RISK = "accepted_risk"
    REOPENED = "reopened"
    CLOSED = "closed"


class EvidenceType(StrEnum):
    EVAL_RUN = "eval_run"
    SECURITY_AUDIT_RUN = "security_audit_run"
    TRACE_INTEGRITY_RUN = "trace_integrity_run"
    AUDIT_INTEGRITY_RUN = "audit_integrity_run"
    REPLAY_INTEGRITY_RUN = "replay_integrity_run"
    PERMISSION_BOUNDARY_RUN = "permission_boundary_run"
    BACKUP_RESTORE_RUN = "backup_restore_run"
    BENCHMARK_RUN = "benchmark_run"
    DATA_INTEGRITY_RUN = "data_integrity_run"
    DIAGNOSTIC_BUNDLE = "diagnostic_bundle"
    RELEASE_REPORT = "release_report"
    VERIFICATION_CLOSURE = "verification_closure"
    MANUAL_REVIEW = "manual_review"


class EvalRunStatus(StrEnum):
    CREATED = "created"
    RUNNING = "running"
    PASSED = "passed"
    FAILED = "failed"


class SecurityAuditStatus(StrEnum):
    CREATED = "created"
    RUNNING = "running"
    PASSED = "passed"
    FAILED = "failed"


class IntegrityCheckType(StrEnum):
    TRACE = "trace"
    AUDIT = "audit"
    REPLAY = "replay"
    PERMISSION_BOUNDARY = "permission_boundary"
    DATA = "data"


class BackupJobStatus(StrEnum):
    CREATED = "created"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class RestoreJobStatus(StrEnum):
    CREATED = "created"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class BenchmarkRunStatus(StrEnum):
    CREATED = "created"
    RUNNING = "running"
    PASSED = "passed"
    FAILED = "failed"


class DiagnosticBundleStatus(StrEnum):
    CREATED = "created"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class ReleaseDecision(StrEnum):
    GO = "go"
    NO_GO = "no_go"
    NEEDS_REVIEW = "needs_review"


class ChatEventType(StrEnum):
    TURN_STARTED = "turn.started"
    CONTEXT_STARTED = "context.started"
    CONTEXT_READY = "context.ready"
    INTENT_DETECTED = "intent.detected"
    MODE_SELECTED = "mode.selected"
    ROUTE_SELECTED = "route.selected"
    MODEL_PLACEHOLDER = "model.placeholder"
    MODEL_STARTED = "model.started"
    MODEL_FALLBACK = "model.fallback"
    MODEL_COMPLETED = "model.completed"
    TASK_CREATED = "task.created"
    TASK_PLANNED = "task.planned"
    TASK_STARTED = "task.started"
    TASK_PAUSED = "task.paused"
    TASK_RESUMED = "task.resumed"
    TASK_COMPLETED = "task.completed"
    TASK_FAILED = "task.failed"
    TASK_CANCELLED_EVENT = "task.cancelled"
    TASK_STEP_STARTED = "task.step_started"
    TASK_STEP_COMPLETED = "task.step_completed"
    TASK_STEP_FAILED = "task.step_failed"
    TOOL_STARTED = "tool.started"
    TOOL_COMPLETED = "tool.completed"
    TOOL_FAILED = "tool.failed"
    APPROVAL_REQUIRED = "approval.required"
    APPROVAL_RESOLVED = "approval.resolved"
    ARTIFACT_CREATED = "artifact.created"
    SKILL_MATCHED = "skill.matched"
    SKILL_STARTED = "skill.started"
    SKILL_COMPLETED = "skill.completed"
    SKILL_FAILED = "skill.failed"
    PLUGIN_INSTALLED = "plugin.installed"
    PLUGIN_ENABLED = "plugin.enabled"
    PLUGIN_DISABLED = "plugin.disabled"
    PLUGIN_REVOKED = "plugin.revoked"
    MCP_SERVER_CONNECTED = "mcp.server_connected"
    MCP_SERVER_DISCONNECTED = "mcp.server_disconnected"
    MCP_TOOLS_SYNCED = "mcp.tools_synced"
    MCP_TOOL_STARTED = "mcp.tool_started"
    MCP_TOOL_COMPLETED = "mcp.tool_completed"
    MCP_TOOL_FAILED = "mcp.tool_failed"
    MCP_RESOURCE_READ = "mcp.resource_read"
    MCP_PROMPT_LOADED = "mcp.prompt_loaded"
    SUPERVISOR_PLANNED = "supervisor.planned"
    PARTICIPANT_SELECTED = "participant.selected"
    PARTICIPANT_CONTEXT_READY = "participant.context_ready"
    SUBTASK_CREATED = "subtask.created"
    SUBTASK_STARTED = "subtask.started"
    SUBTASK_COMPLETED = "subtask.completed"
    SUBTASK_FAILED = "subtask.failed"
    COLLABORATION_ROUND_STARTED = "collaboration.round_started"
    COLLABORATION_ROUND_COMPLETED = "collaboration.round_completed"
    HOST_REVIEW_STARTED = "host.review_started"
    HOST_REVIEW_COMPLETED = "host.review_completed"
    HOST_SYNTHESIS_COMPLETED = "host.synthesis_completed"
    SHELL_SWITCH_PREVIEWED = "shell.switch_previewed"
    SHELL_SWITCHED = "shell.switched"
    PLANNER_SELECTED = "planner.selected"
    AGENT_LOOP_STARTED = "agent.loop_started"
    AGENT_ITERATION_COMPLETED = "agent.iteration_completed"
    AGENT_STOPPED = "agent.stopped"
    TASK_OBSERVATION_CREATED = "task.observation_created"
    TASK_RETRY_PLAN_CREATED = "task.retry_plan_created"
    TASK_REFLECTION_CANDIDATE_CREATED = "task.reflection_candidate_created"
    RESPONSE_DELTA = "response.delta"
    RESPONSE_COMPLETED = "response.completed"
    MEMORY_CANDIDATE = "memory.candidate"
    MEMORY_WRITTEN = "memory.written"
    MEMORY_UPDATED = "memory.updated"
    MEMORY_ARCHIVED = "memory.archived"
    MEMORY_CORRECTION_APPLIED = "memory.correction_applied"
    TURN_CANCELLED = "turn.cancelled"
    TURN_RECOVERY_STARTED = "turn.recovery_started"
    TURN_RECOVERY_DIAGNOSED = "turn.recovery_diagnosed"
    TURN_RECOVERY_ACTION = "turn.recovery_action"
    TURN_RECOVERY_COMPLETED = "turn.recovery_completed"
    TURN_COMPLETED = "turn.completed"
    TURN_FAILED = "turn.failed"


class MessageRole(StrEnum):
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"
    TOOL = "tool"


class MemberStatus(StrEnum):
    ONLINE = "online"
    BUSY = "busy"
    OFFLINE = "offline"
    NEEDS_CONFIGURATION = "needs_configuration"


class BrainProvider(StrEnum):
    OPENAI_COMPATIBLE = "openai_compatible"
    OLLAMA = "ollama"
    VLLM = "vllm"
    CUSTOM_OPENAI_COMPATIBLE = "custom_openai_compatible"
    LOCAL_PLACEHOLDER = "local_placeholder"


class BrainStatus(StrEnum):
    NOT_CONFIGURED = "not_configured"
    CONFIGURED = "configured"
    CHECKING = "checking"
    HEALTHY = "healthy"
    UNHEALTHY = "unhealthy"
    DISABLED = "disabled"


class PrivacyLevel(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class IntentType(StrEnum):
    CHAT = "chat"
    QUESTION_ANSWER = "question_answer"
    CREATIVE_WRITING = "creative_writing"
    SUMMARIZATION = "summarization"
    MEMORY_QUERY = "memory_query"
    SYSTEM_SETTINGS = "system_settings"
    TASK_EXECUTION = "task_execution"


class TurnStatus(StrEnum):
    CREATED = "created"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    RETRIED = "retried"


class FinishReason(StrEnum):
    STOP = "stop"
    LENGTH = "length"
    CANCELLED = "cancelled"
    ERROR = "error"
    TOOL_REQUIRED = "tool_required"


class TaskMode(StrEnum):
    DIRECT = "direct"
    DIRECT_WITH_MEMORY = "direct_with_memory"
    WORKFLOW = "workflow"
    AGENT = "agent"
    SUPERVISOR = "supervisor"


class TaskStatus(StrEnum):
    CREATED = "created"
    DRAFT = "draft"
    PLANNING = "planning"
    PARTICIPANT_SELECTING = "participant_selecting"
    PLANNED = "planned"
    PRECHECK_FAILED = "preflight_failed"
    RUNNING = "running"
    WAITING_APPROVAL = "waiting_approval"
    PAUSED = "paused"
    SYNTHESIZING = "synthesizing"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    ARCHIVED = "archived"


class CapabilityStatus(StrEnum):
    AVAILABLE = "available"
    NOT_IMPLEMENTED = "not_implemented"
    DISABLED = "disabled"


class ApprovalStatus(StrEnum):
    PENDING = "pending"
    APPROVED = "approved"
    DENIED = "denied"
    EDITED = "edited"


class MemoryLayer(StrEnum):
    WORKING = "working"
    SESSION = "session"
    EPISODIC = "episodic"
    SEMANTIC = "semantic"
    PROCEDURAL = "procedural"
    ASSET = "asset"
    TEMPORAL = "temporal"


class ModelRouteName(StrEnum):
    LOCAL_FAST = "local_fast"
    LOCAL_MAIN = "local_main"
    CLOUD_STRONG = "cloud_strong"
    TOOL_SPECIALIZED = "tool_specialized"


class RiskLevel(StrEnum):
    R0 = "R0"
    R1 = "R1"
    R2 = "R2"
    R3 = "R3"
    R4 = "R4"
    R5 = "R5"
    R6 = "R6"
    R7 = "R7"


class AssetCategory(StrEnum):
    BRAIN = "brain"
    ACCOUNT = "account"
    WALLET = "wallet"
    HARDWARE = "hardware"
    KNOWLEDGE_BASE = "knowledge_base"


class TraceStatus(StrEnum):
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class TraceSpanStatus(StrEnum):
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class TraceSpanType(StrEnum):
    APP_STARTUP = "app.startup"
    CONFIG_LOAD = "config.load"
    DB_MIGRATION = "db.migration"
    SHELL_LOAD = "shell.load"
    BOOTSTRAP_ORGANIZATION = "bootstrap.organization"
    API_REQUEST = "api.request"
    CHAT_TURN = "chat.turn"
    CHAT_PLACEHOLDER_TURN = "chat.placeholder_turn"
    MESSAGE_PERSIST_USER = "message.persist.user"
    MESSAGE_PERSIST_ASSISTANT = "message.persist.assistant"
    RESPONSE_PLACEHOLDER = "response.placeholder"
    CONTEXT_BUILD = "context.build"
    CONTEXT_SUMMARY_READ = "context.summary.read"
    BRAIN_INTENT = "brain.intent"
    BRAIN_MODE_SELECT = "brain.mode_select"
    BRAIN_DECISION_CHAIN = "brain.decision_chain"
    BRAIN_CONTEXT_DECISION = "brain.context_decision"
    BRAIN_CLARIFICATION_DECISION = "brain.clarification_decision"
    DIALOGUE_STATE = "dialogue.state"
    SEMANTIC_INTENT = "brain.semantic_intent"
    LOW_CONFIDENCE_REVIEW = "brain.low_confidence_review"
    SEMANTIC_REVIEW_STARTED = "semantic_review.started"
    SEMANTIC_REVIEW_MODEL_CALL = "semantic_review.model_call"
    SEMANTIC_REVIEW_SCHEMA_VALIDATION = "semantic_review.schema_validation"
    SEMANTIC_REVIEW_MERGE = "semantic_review.merge"
    SEMANTIC_REVIEW_FALLBACK = "semantic_review.fallback"
    MODEL_ROUTE = "model.route"
    MODEL_FALLBACK = "model.fallback"
    CONVERSATION_TITLE = "conversation.title"
    TURN_CANCEL = "turn.cancel"
    TURN_FAILED = "turn.failed"
    TURN_RECOVERY = "turn.recovery"
    MEMORY_SEARCH = "memory.search"
    MEMORY_EXTRACT = "memory.extract"
    MEMORY_SCORE = "memory.score"
    MEMORY_DEDUPE = "memory.dedupe"
    MEMORY_CONFLICT = "memory.conflict"
    MEMORY_COMPRESS = "memory.compress"
    MEMORY_CORRECTION = "memory.correction"
    MEMORY_ARCHIVE = "memory.archive"
    MEMORY_DELETE = "memory.delete"
    MEMORY_VECTOR_UPSERT = "memory.vector.upsert"
    ASSET_QUERY = "asset.query"
    ASSET_VERIFY = "asset.verify"
    ASSET_HANDLE_ISSUE = "asset.handle.issue"
    ASSET_HANDLE_VALIDATE = "asset.handle.validate"
    ASSET_HANDLE_REVOKE = "asset.handle.revoke"
    CAPABILITY_DECISION = "capability.decision"
    CAPABILITY_EDGE_CREATE = "capability.edge.create"
    CAPABILITY_EDGE_UPDATE = "capability.edge.update"
    KNOWLEDGE_INDEX = "knowledge.index"
    KNOWLEDGE_CHUNK = "knowledge.chunk"
    KNOWLEDGE_SEARCH = "knowledge.search"
    SECRET_REF_ROTATE = "secret.ref.rotate"
    MODEL_CALL = "model.call"
    TASK_PLAN = "task.plan"
    PLANNER_SELECT = "planner.select"
    TASK_CREATE = "task.create"
    TASK_PREFLIGHT = "task.preflight"
    TASK_RUN = "task.run"
    TASK_PAUSE = "task.pause"
    TASK_RESUME = "task.resume"
    TASK_CANCEL_SPAN = "task.cancel"
    TASK_STEP_RUN = "task.step.run"
    TASK_STEP_RETRY = "task.step.retry"
    TOOL_SCHEMA_VALIDATE = "tool.schema.validate"
    TOOL_PREFLIGHT = "tool.preflight"
    TOOL_CALL = "tool.call"
    TOOL_RESULT_REDACT = "tool.result.redact"
    APPROVAL_CREATE = "approval.create"
    APPROVAL_RESOLVE = "approval.resolve"
    ARTIFACT_WRITE = "artifact.write"
    TASK_REPLAY = "task.replay"
    TASK_REFLECTION = "task.reflection"
    AGENT_OBSERVE = "agent.observe"
    AGENT_PLAN = "agent.plan"
    AGENT_ACT = "agent.act"
    AGENT_EVALUATE = "agent.evaluate"
    AGENT_REVISE = "agent.revise"
    AGENT_STOP = "agent.stop"
    TASK_OBSERVATION_CREATE = "task.observation.create"
    SAFETY_EVALUATE = "safety.evaluate"
    SAFETY_PRIVACY_CLASSIFY = "safety.privacy_classify"
    APPROVAL_WAIT = "approval.wait"
    RESPONSE_COMPOSE = "response.compose"
    CHAT_EXPERIENCE = "chat.experience"
    CHAT_CLARIFICATION = "chat.clarification"
    MEMORY_WRITE = "memory.write"
    PLUGIN_INSTALL = "plugin.install"
    PLUGIN_VALIDATE = "plugin.validate"
    PLUGIN_PERMISSION_PREVIEW = "plugin.permission_preview"
    PLUGIN_ENABLE = "plugin.enable"
    PLUGIN_DISABLE = "plugin.disable"
    PLUGIN_REVOKE = "plugin.revoke"
    SKILL_MATCH = "skill.match"
    SKILL_RUN = "skill.run"
    SKILL_STEP = "skill.step"
    SKILL_EVAL = "skill.eval"
    SKILL_CANDIDATE_PROMOTE = "skill.candidate.promote"
    MCP_SERVER_REGISTER = "mcp.server.register"
    MCP_SERVER_CONNECT = "mcp.server.connect"
    MCP_SERVER_SYNC = "mcp.server.sync"
    MCP_SERVER_DISCONNECT = "mcp.server.disconnect"
    MCP_TOOL_CALL = "mcp.tool.call"
    MCP_RESOURCE_READ = "mcp.resource.read"
    MCP_PROMPT_LOAD = "mcp.prompt.load"
    SUPERVISOR_PLAN = "supervisor.plan"
    SUPERVISOR_PARTICIPANT_SELECT = "supervisor.participant_select"
    SUPERVISOR_ROUND_RUN = "supervisor.round.run"
    RELEASE_GATE_RUN = "release.gate.run"
    RELEASE_EVIDENCE_COLLECT = "release.evidence.collect"
    RELEASE_FINDING_TRIAGE = "release.finding.triage"
    EVAL_RUN = "eval.run"
    SECURITY_AUDIT_RUN = "security.audit.run"
    SECRET_SCAN = "secret.scan"
    INTEGRITY_TRACE = "integrity.trace"
    INTEGRITY_AUDIT = "integrity.audit"
    INTEGRITY_REPLAY = "integrity.replay"
    BACKUP_CREATE = "backup.create"
    RESTORE_VALIDATE = "restore.validate"
    BENCHMARK_RUN = "benchmark.run"
    DIAGNOSTIC_EXPORT = "diagnostic.export"
    RELEASE_REPORT_GENERATE = "release.report.generate"
    BACKGROUND_WORKER = "background.worker"
    VECTOR_SYNC = "vector.sync"
    PERSONA_PROFILE = "persona.profile"
    HEART_STATE = "heart.state"
    SUBTASK_CONTEXT_BUILD = "subtask.context.build"
    SUBTASK_RUN = "subtask.run"
    SUBTASK_MERGE = "subtask.merge"
    HOST_REVIEW = "host.review"
    HOST_SYNTHESIS = "host.synthesis"
    MEMBER_MEMORY_WRITE = "member.memory.write"
    COLLABORATION_REPLAY = "collaboration.replay"
    SHELL_SWITCH_PREVIEW = "shell.switch.preview"
    SHELL_SWITCH = "shell.switch"
    SHELL_TEMPLATE_APPLY = "shell.template.apply"
